elements.obsidian = {
	color: ["#343434", "#313639"],
	behavior: behaviors.SOLID,
	category: "solids",
	state: "solid",
    density: 2380,
    reactions: {
        "sand": { elem1: "obsidian_shard" },
        "dirt": { elem1: "obsidian_shard" },
        "rock": { elem1: "obsidian_shard" },
        "mudstone": { elem1: "obsidian_shard" },
        "packed_snow": { elem1: "obsidian_shard" },
        "gravel": { elem1: "obsidian_shard" },
        "clay": { elem1: "obsidian_shard" },
        "clay_soil": { elem1: "obsidian_shard" },
        "permafrost": { elem1: "obsidian_shard" },
        "mulch": { elem1: "obsidian_shard" },
        "basalt": { elem1: "obsidian_shard" },
        "tuff": { elem1: "mud" },
        "limestone": { elem1: "obsidian_shard" },
        "quicklime": { elem1: "obsidian_shard" },
        "slaked_lime": { elem1: "obsidian_shard" },
        }
    },
    elements.obsidian_shard = {
	color: ["#343434", "#313639"],
	behavior: behaviors.POWDER,
	category: "powders",
	state: "solid",
    density: 2380,
    reactions: {
            "glue": { elem1: "obsidian" },
            }
    },
elements.pumice = {
    color: "#bac0b4",
    behavior: behaviors.POWDER,
    category: "land",
    state: "solid",
    density: 550,
     tempHigh: 900,
    stateHigh: "magma",
    hardness: 0.5,
    },
elements.magma.stateLow = ["basalt","basalt","basalt","pumice","basalt","rock","obsidian_shard","obsidian"],
    elements.eruption = {
    color:  ["#ff6f00","#ff8c00","#ff4d00"],
    behavior: [
        "XX|M1|XX",
        "XX|DL%1|XX",
        "CR:magma|CR:magma|CR:magma",
    ],
    category: "weapons",
    state: "solid",
    temp:1200,
    density: 2725,
};