elements.anti_mudstone = {
	color: "#4a341e",
	behavior: [
		"XX|M1|XX",
		"SP|XX|SP",
		"XX|XX|XX",
	],
	tempHigh:1200,
	stateHigh: "molten_dirt",
	category: "center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.vertical_mudstone_1 = {
	name: "<|- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|SP|XX",
		"M1|XX|XX",
		"XX|SP|XX",
	],
	tempHigh:1200,
	stateHigh: "molten_dirt",
	category: "center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.vertical_mudstone_2 = {
	name: "|>- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|SP|XX",
		"XX|XX|M1",
		"XX|SP|XX",
	],
	tempHigh:1200,
	stateHigh: "molten_dirt",
	category: "center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_br_mudstone_1 = {
	name: "L\\- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|XX",
		"XX|XX|XX",
		"M1|XX|SP",
	],
	tempHigh:1200,
	stateHigh: "molten_dirt",
	category: "center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_br_mudstone_2 = {
	name: "\\'- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|M1",
		"XX|XX|XX",
		"XX|XX|SP",
	],
	tempHigh:1200,
	stateHigh: "molten_dirt",
	category: "center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tr_bl_mudstone_1 = {
	name: "/J- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|XX|SP",
		"XX|XX|XX",
		"SP|XX|M1",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tr_bl_mudstone_2 = {
	name: "r/- mudstone",
	color: "#4a341e",
	behavior: [
		"M1|XX|SP",
		"XX|XX|XX",
		"SP|XX|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tr_tl_mudstone = {
	name: "V- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|SP",
		"XX|XX|XX",
		"XX|M1|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.br_bl_mudstone = {
	name: "^- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|M1|XX",
		"XX|XX|XX",
		"SP|XX|SP",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_bl_mudstone = {
	name: ">- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|XX",
		"XX|XX|M1",
		"SP|XX|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tr_br_mudstone = {
	name: "<- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|XX|SP",
		"M1|XX|XX",
		"XX|XX|SP",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tm_mr_mudstone = {
	name: "-,- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|SP|XX",
		"XX|XX|SP",
		"M1|XX|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.ml_tm_mudstone = {
	name: "r- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|SP|XX",
		"SP|XX|XX",
		"XX|XX|M1",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.ml_bm_mudstone = {
	name: "L- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|XX|M1",
		"SP|XX|XX",
		"XX|SP|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.bm_mr_mudstone = {
	name: "J- mudstone",
	color: "#4a341e",
	behavior: [
		"M1|XX|XX",
		"XX|XX|SP",
		"XX|SP|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "non- center intersecting s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_bl_tr_br_mudstone_1 = {
	name: "Xv- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|SP",
		"XX|XX|XX",
		"SP|M1|SP",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_bl_tr_br_mudstone_2 = {
	name: "X^- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|M1|SP",
		"XX|XX|XX",
		"SP|XX|SP",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_bl_tr_br_mudstone_3 = {
	name: "X<- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|SP",
		"M1|XX|XX",
		"SP|XX|SP",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_bl_tr_br_mudstone_4 = {
	name: "X>- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|SP",
		"XX|XX|M1",
		"SP|XX|SP",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.ml_tm_bm_mr_mudstone_1 = {
	name: "+ L- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|SP|XX",
		"SP|XX|SP",
		"M1|SP|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.ml_tm_bm_mr_mudstone_2 = {
	name: "+ -,- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|SP|M1",
		"SP|XX|SP",
		"XX|SP|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.ml_tm_bm_mr_mudstone_3 = {
	name: "+r- mudstone",
	color: "#4a341e",
	behavior: [
		"M1|SP|XX",
		"SP|XX|SP",
		"XX|SP|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.ml_tm_bm_mr_mudstone_4 = {
	name: "+J- mudstone",
	color: "#4a341e",
	behavior: [
		"XX|SP|XX",
		"SP|XX|SP",
		"XX|SP|M1",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "cross s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
},

elements.tl_rm_mudstone_1 = {
	name: "`-v- mudstone",
	color: "#4a341e",
	behavior: [
		"SP|XX|XX",
		"XX|XX|SP",
		"XX|M1|XX",
	],
	tempHigh: 1200,
	stateHigh: "molten_dirt",
	category: "other s p- line mudstones",
	state: "solid",
	density: 1250,
	breakInto: "dirt",
}
