elements.lab = {
    color: "#ff0000",
    behaviorOn: behaviors.WALL,
    behavior: [
        "CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall",
        "CR:wall|DL|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|CR:wall|CR:wall|CR:wall|XX|CR:wall|CR:wall|CR:wall|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall|CR:wall|CR:wall|CR:wire|xx|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|XX|XX|XX|CR:ecloner|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall|CR:wall|CR:wall|CR:wire|CR:wall|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:glass|XX|XX|CR:sensor|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:glass|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall|CR:wall|XX|CR:wall|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|XX|XX|XX|XX|XX|XX|XX|CR:wall",
        "CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|XX|CR:wall|CR:wall|CR:wall",
        "CR:wall|CR:wire|CR:wall|CR:wire|CR:wall|CR:wire|CR:wall|CR:wire|CR:wall|XX|XX|XX|CR:wall",
        "CR:wall|CR:wire|CR:wire|CR:wire|CR:wire|CR:wire|CR:wire|CR:wire|CR:wall|XX|XX|XX|CR:wall",
        "CR:wall|CR:wall|CR:wall|CR:wall|CR:wire|CR:wall|CR:wall|CR:wall|CR:wire|CR:sensor|XX|XX|CR:wall",
        "CR:wall|CR:wall|CR:wall|CR:wall|CR:wire|CR:wire|CR:wire|CR:wire|CR:wire|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall|CR:wall",
    ],
    category: "lab",
    state: "solid",
}
// i know it looks messy but it works
// and u can replace the wall on top of the 4 wire in the testing chamber with whatever machines u want
// if u dont belive me test it but place it in the center of the canvas
