elements.the_snail = {
	color: "#5c3104",
    behavior: [
        "XX|XX|XX",
        "XX|FX%0.25|M2%0.5 AND BO",
        "XX|M1|XX",
    ],
    reactions: {
        "salt": { elem1: "quicklime", elem2: null },
        "dirty_water": { elem2:"water", chance:0.05, func:behaviors.FEEDPIXEL },
        "broth": { elem2:"water", chance:0.05, func:behaviors.FEEDPIXEL },
        "tea": { elem2:"water", chance:0.05, func:behaviors.FEEDPIXEL },
        "plant": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "evergreen": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "cactus": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "dead_plant": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "worm": { elem2:null, chance:0.01, func:behaviors.FEEDPIXEL },
        "mushroom_spore": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "grass": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "herb": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "lettuce": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "grass_seed": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "algae": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "mushroom_cap": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "mushroom_stalk": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "mushroom_gill": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "lichen": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "hyphae": { elem2:"dirt", chance:0.05, func:behaviors.FEEDPIXEL },
        "mycelium": { elem2:"dirt", chance:0.05, func:behaviors.FEEDPIXEL },
        "pumpkin": { elem2:null, chance:0.01, func:behaviors.FEEDPIXEL },
        "calcium": { elem2:null, chance:0.01, func:behaviors.FEEDPIXEL },
        "limestone": { elem2:null, chance:0.001, func:behaviors.FEEDPIXEL },
        "quicklime": { elem2:null, chance:0.01, func:behaviors.FEEDPIXEL },
        "slaked_lime": { elem2:null, chance:0.01, func:behaviors.FEEDPIXEL },
        "paper": { elem2:null, chance:0.01, func:behaviors.FEEDPIXEL },
        "pickle": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "grape": { elem2:null, chance:0.01, func:behaviors.FEEDPIXEL },
        "body": { elem1:"crasher" },
        "head": { elem1:"crasher" },
    },
    category: "special",
    state: "solid",
    hardness: 1,
    conduct: 0.16,
    alias: "The Immortal Snail",
};

elements.crasher = {
    onSelect: function() {
        logMessage("WARNING: DO NOT PLACE THIS! This WILL crash your game and is only used for the immortal snail.");
    },
	color: "#FFFFFF",
    behavior: [
        "XX|CL|XX",
        "CL|EX:10000000000>flash|CL",
        "XX|CL|XX",
    ],
    category: "special",
    insulate: true,
    hardness: 1,
    noMix: true,
    hidden: true,
};