elements.Land_Category_Clearer = {
    color: "#FFFFFF",
    behavior: behaviors.POWDER,
    category: "CLEARING",
    state: "solid",
    statehigh: "carbon_dioxide",
    tempHigh: 100000,
    tempLow: -100000,
    statelow: "carbon_dioxide",
    reactions: {
        "sand": {elem1: "null", elem2: "acid" },
        "dirt": {elem1: "null", elem2: "acid" },
        "mud": {elem1: "null", elem2: "acid" },
        "wetsand": {elem1: "null", elem2: "acid" },
        "rock": {elem1: "null", elem2: "acid" },
        "rockwall": {elem1: "null", elem2: "acid" },
        "mudstone": {elem1: "null", elem2: "acid" },
        "packedsand": {elem1: "null", elem2: "acid" },
        "snow": {elem1: "null", elem2: "acid" },
        "gravel": {elem1: "null", elem2: "acid" },
        "clay": {elem1: "null", elem2: "acid" },
        "claysoil": {elem1: "null", elem2: "acid" },
        "permafrost": {elem1: "null", elem2: "acid" },
        "mycelium": {elem1: "null", elem2: "acid" },
        "mulch": {elem1: "null", elem2: "acid" },
        "basalt": {elem1: "null", elem2: "acid" },
        "tuff": {elem1: "null", elem2: "acid" },
        "limestone": {elem1: "null", elem2: "acid" },
    }
};
