elements.Land_Category_Clearer = {
    color: "#FFFFFF",
    behavior: behaviors.POWDER,
    category: "CLEARING",
    state: "solid",
    statehigh: "carbon_dioxide",
    tempHigh: 100000,
    tempLow: -100000,
    statelow: "carbon_dioxide",
    reactions: {
        "sand": {elem1: "null", elem2: "acid" },
        "dirt": {elem1: "null", elem2: "acid" },
        "mud": {elem1: "null", elem2: "acid" },
        "wetsand": {elem1: "null", elem2: "acid" },
        "rock": {elem1: "null", elem2: "acid" },
        "rockwall": {elem1: "null", elem2: "acid" },
        "mudstone": {elem1: "null", elem2: "acid" },
        "packedsand": {elem1: "null", elem2: "acid" },
        "snow": {elem1: "null", elem2: "acid" },
        "gravel": {elem1: "null", elem2: "acid" },
        "clay": {elem1: "null", elem2: "acid" },
        "claysoil": {elem1: "null", elem2: "acid" },
        "permafrost": {elem1: "null", elem2: "acid" },
        "mycelium": {elem1: "null", elem2: "acid" },
        "mulch": {elem1: "null", elem2: "acid" },
        "basalt": {elem1: "null", elem2: "acid" },
        "tuff": {elem1: "null", elem2: "acid" },
        "limestone": {elem1: "null", elem2: "acid" },
    }
};
elements.Liquids_Category_Clearer = {
    color: "#FFFFFF",
    behavior: behaviors.LIQUID,
    category: "CLEARING",
    state: "solid",
    statehigh: "carbon_dioxide",
    tempHigh: 100000,
    tempLow: -100000,
    statelow: "carbon_dioxide",
    reactions: {
        "water": {elem1: "null", elem2: "acid" },
        "salt_water": {elem1: "null", elem2: "acid" },
        "magma": {elem1: "null", elem2: "acid" },
        "slime": {elem1: "null", elem2: "acid" },
        "cement": {elem1: "null", elem2: "acid" },
        "oil": {elem1: "null", elem2: "acid" },
        "lamp_oil": {elem1: "null", elem2: "acid" },
        "foam": {elem1: "null", elem2: "acid" },
        "acid": {elem1: "null", elem2: "strange_matter" },
        "glue": {elem1: "null", elem2: "acid" },
        "soda": {elem1: "null", elem2: "acid" },
        "juice": {elem1: "null", elem2: "acid" },
        "milk": {elem1: "null", elem2: "acid" },
        "vinegar": {elem1: "null", elem2: "acid" },
        "alcohol": {elem1: "null", elem2: "acid" },
        "soap": {elem1: "null", elem2: "acid" },
        "bleach": {elem1: "null", elem2: "acid" },
        "dye": {elem1: "null", elem2: "acid" },
        "ink": {elem1: "null", elem2: "acid" },
        "mercury": {elem1: "null", elem2: "acid" },
        "blood": {elem1: "null", elem2: "acid" },
        "vaccine": {elem1: "null", elem2: "acid" },
        "poision": {elem1: "null", elem2: "acid" },
        "antdote": {elem1: "null", elem2: "acid" },
        "honey": {elem1: "null", elem2: "acid" },
        "sap": {elem1: "null", elem2: "acid" },
        "caramel": {elem1: "null", elem2: "acid" },
        "molasses": {elem1: "null", elem2: "acid" },
        "ketchup": {elem1: "null", elem2: "acid" },
        "mayo": {elem1: "null", elem2: "acid" },
        "liquid_oxygen": {elem1: "null", elem2: "acid" },
        "liquid_nitrogen": {elem1: "null", elem2: "acid" },
    }
};
